### ISSUE TITLE
[App Request] ConvertX Self hosted general file conversion tool

### ISSUE THREAD

**Issue by douglasg14b** [azukaar/cosmos-servapps-official#168]
https://github.com/C4illin/ConvertX

```yaml
# docker-compose.yml
services:
  convertx: 
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=aLongAndSecretStringUsedToSignTheJSONWebToken1234 # will use randomUUID() if unset
    volumes:
      - convertx:/app/data
```

## Envs

| Name                      | Default | Description |
|---------------------------|---------|-------------|
| JWT_SECRET                | when unset it will use the value from randomUUID() | A long and secret string used to sign the JSON Web Token |
| ACCOUNT_REGISTRATION      | false | Allow users to register accounts |
| HTTP_ALLOWED              | false | Allow HTTP connections, only set this to true locally |
| ALLOW_UNAUTHENTICATED     | false | Allow unauthenticated users to use the service, only set this to true locally |
| AUTO_DELETE_EVERY_N_HOURS | 24 | Checks every n hours for files older then n hours and deletes them, set to 0 to disable |
| WEBROOT                   | "" | The address to the root path setting this to "/convert" will serve the website on "example.com/convert/" |
